export enum TaskStatus {
    STARTED = "STARTED",
    STOPPED = "STOPPED",
    FINISHED = "FINISHED",
    WAITING_FOR_INFO = "WAITING_FOR_INFO",
    FAIL = "FAIL",
    TRANSFERRED_TO_NEXT_SPRINT = "TRANSFERRED_TO_NEXT_SPRINT"
}
